### ISSUE TITLE
projects improvements

### ISSUE THREAD

**Issue by treaz** [robertsci/SmartList#1]
- use the latest java in pom.xml
- create readme.md in which you explain how I can run the project myself; also valid for the test. Basically, write everything in the readme that you would forget and have to research again if you stop working on the project for 1 year
- look into project lombok especially for KauflandStore
- use the[ java core HTTP client ](https://howtoprogram.xyz/2017/10/19/java-9-http-2-client-api-example/)

**Comment by treaz** [comment]
why closed?

**Comment by treaz** [comment]
stii cine sunt, nu? :) o sa iti raspund la mail putin mai incolo

**Comment by robertsci** [comment]
Salut Horia, da stiu.

Din greseala l-am inchis. Am intrat de pe telefon si am apasat fara sa
vreau pe closed. Dar nu-ti face griji, diseara fac schimbările pe care mi
le-ai spus.

Mersi,
Robert

**Comment by robertsci** [comment]
Sorry for closing it, by mistake :D

**Comment by treaz** [comment]
for lombok, look into @Data, no need to do manually @Getter @Setter

**Comment by robertsci** [comment]
Done, it's in the next commit. I don't remember why i thought yesterdy that it's a good idea to use @getter and @setter. Also for the Http library, i have started studying a small course about how to use it. Thank you :D

**Comment by treaz** [comment]
@robertsci if you've made the change, commit it: https://duckduckgo.com/?q=keep+commits+small&t=ffab&ia=web

**Comment by robertsci** [comment]
So i have created a basic Kanban and added the tasks there
