### ISSUE TITLE
create UML for the main objects in app

### ISSUE THREAD

**Issue by treaz** [robertsci/SmartList#4]

**Comment by treaz** [comment]
@robertsci no one really uses UML diagrams in reality. Most of the time that's for architects, as an app developer, we generally use predefined patterns of interaction.
So, I'm curious, what you would achieve by creating UML diagrams

**Comment by robertsci** [comment]
I was thinking that it may help me implement them easier, if i think at them once, and then write the code. This doesn't necessarily mean that if i think at an edge case when i write the code i would not change, just to have some sort of direction

**Comment by treaz** [comment]
Robert, I'll help you out on this. Write the code and then we see lieve how it makes sense to create the separation between classes, interfaces, methods, etc. Besides, spring will force you into a specific type of architecture anyway :)
